check-ticks: 4
effect-y: -20
teleport-y: -40
entity-teleport-y: -30
world-border-buffer: 50

exit:
  world:
    enabled: true
    send-to: surface
    surface:
      safe-scan:
        enabled: true
        step: 8
        tries: 5

  world_nether:
    enabled: true
    send-to: surface
    surface:
      safe-scan:
        enabled: true
        step: 16
        tries: 5

  world_the_end:
    enabled: true
    send-to: sky
    sky:
      world: world
      y: 500
      messages:
      - '&3You fell out of the sky!'
      - '&3Whoopsie!'
      effects:
      - ==: PotionEffect
        effect: 15
        duration: 200
        amplifier: 3
        ambient: true
        has-particles: false
        has-icon: false
      - ==: PotionEffect
        effect: 9
        duration: 300
        amplifier: 1
        ambient: true
        has-particles: false
        has-icon: false
      teleport-mobs:
      - HORSE
      - SKELETON_HORSE
      - ZOMBIE_HORSE
      
enter:
  world:
    fail-safe-location:
      x: 0
      y: 70
      z: 0
    exclusion-zones:
    - x: 0
      z: 0
      radius: 500

  world_nether:
    fail-safe-location:
      x: 0
      y: 70
      z: 0
    exclusion-zones: []

  world_the_end:
    fail-safe-location:
      x: 0
      y: 70
      z: 0
    exclusion-zones: []
